using System;
using System.Collections.Generic;
using System.Configuration;
using System.IO;
using System.Linq;
using System.Net;
using System.Net.Mail;
using System.Web;
using System.Web.UI;

namespace uk_forest.common_email
{
    public class MailsHandling
    {
        public static void SendEmails_old(string sendTo, string sendSubject, string strArea, bool mailLinkToBeGiven = true)
        {
            try
            {
                System.Net.Mail.MailMessage objEmail = new System.Net.Mail.MailMessage();
                StringWriter sw = new StringWriter();
                HtmlTextWriter htmltw = new HtmlTextWriter(sw);
                htmltw.RenderBeginTag("html");
                htmltw.RenderBeginTag("body");
                htmltw.WriteLine(strArea + "<br />");

                if (mailLinkToBeGiven)
                    htmltw.WriteLine("<br />Please refer on-line application <a href = " + System.Configuration.ConfigurationManager.AppSettings["AppURL"].ToString() + ">" + System.Configuration.ConfigurationManager.AppSettings["AppURL"].ToString() + "</a> for further details.<br />");

                htmltw.WriteLine("<br />Regards,<br />");
                htmltw.WriteLine("IUFMP Web mail service<br /><br />");
                htmltw.WriteLine("<b>-----------------------------------------------------------");
                htmltw.WriteLine("<br />This is an autogenerated mail, please do not reply.<br />");
                htmltw.WriteLine("-----------------------------------------------------------</b>");
                htmltw.RenderEndTag();
                htmltw.RenderEndTag();

                if (sendTo.StartsWith(","))
                    sendTo = sendTo.Remove(0, 1);

                if (sendTo.EndsWith(","))
                    sendTo = sendTo.Remove(sendTo.Length - 1, 1);

                if (sendTo != "")
                    objEmail.To.Add(sendTo);

                objEmail.Subject = sendSubject;
                objEmail.Body = sw.ToString();
                objEmail.IsBodyHtml = true;
                objEmail.Priority = System.Net.Mail.MailPriority.Normal;
                System.Net.Mail.SmtpClient cls = new SmtpClient();

                cls.Send(objEmail);
                //BusinessLayer.Alert.ShowSuccess("Mail sent successfully");
            }
            catch (Exception ex)
            {
                throw ex;
            }

        }
        public static void send_email_pass_chnge(string to, string name, string otp, string employee_no, string pwd)
        {
            string email_id;
            string password;
            try
            {
                email_id = ConfigurationManager.AppSettings["email_id"];
                password = ConfigurationManager.AppSettings["email_id_password"];
                string textBody = null;
                using (MailMessage mm = new MailMessage(email_id, to))
                {

                    mm.Subject = "One Time Password !! Don't Share With Anyone";
                    textBody += "Dear " + "\r\n" + name + "\r\n" + ",\r\n\r\n<br><br>" + "This Email is confirmation for your password has been change. Do not share with anyone  \r\n</b>";
                    textBody += "\r\n\r\n<br>" + "Your Employee number is : " + "\r\n" + "<b>" + employee_no + "</b>" + "\r\n\r\n<br>";

                    //textBody += "This is your one time password (OTP). Do not share with anyone \r\n</b>";
                    textBody += "\r\n\r\n<br>" + "And Your New Password is : " + "\r\n" + "<b>" + otp + "</b>" + "\r\n\r\n<br>";
                    //textBody += "\r\n\r\n<br><br>" + "This OTP is only for verification of your email.";
                    //textBody += "\r\n\r\n<br><br>" + "If you have any questions leading up to the Beat Planner, feel free to reply to this email." + "\r\n\r\n<br><br>" + "We look forward to seeing you on" + "\r\n\r\n<b>" + " Beat Planner!" + "\r\n\r\n</b>";
                    textBody += "\r\n\r\n <br><br><br><br><br><br>" + "Thanks & Regards," + "\r\n\r\n<br><b>" + "\r\n<br>" + "Excel Geomatics Private Ltd, Noida" + "\r\n\r\n<br><b><br><br><br>";

                    textBody += "<b>" + "Confidentiality Notice: " + "</b>" + "This e-mail message, including any attachments, is for the sole use of the intended recipient(s) and may contain confidential and privileged information. Any unauthorized review, use, disclosure or distribution is prohibited. If you are not the intended recipient, please contact the sender by reply e-mail and destroy all copies of the original message. Please do not print this email unless it is absolutely necessary. Spread environmental awareness.";

                    mm.Body = textBody;
                    mm.IsBodyHtml = true;
                    SmtpClient smtp = new SmtpClient();
                    smtp.Host = "mail.edusokouniversity.edu.ng";
                    //smtp.EnableSsl = true;
                    NetworkCredential NetworkCred = new NetworkCredential(email_id, password);
                    smtp.UseDefaultCredentials = true;
                    smtp.Credentials = NetworkCred;
                    smtp.Port = 464;
                    //smtp.Timeout = 300000;
                    smtp.Send(mm);
                    //registration_log(mm.Subject.ToString(), mm.Body.ToString());
                }
            }
            catch (Exception ex)
            {

            }
        }

        public static void SendOTPEmails(string sendTo, string sendSubject, string stroptmsg)
        {
            try
            {
                System.Net.Mail.MailMessage objEmail = new System.Net.Mail.MailMessage();
                StringWriter sw = new StringWriter();
                HtmlTextWriter htmltw = new HtmlTextWriter(sw);
                htmltw.RenderBeginTag("html");
                htmltw.RenderBeginTag("body");
                htmltw.WriteLine(stroptmsg + "<br />");


                htmltw.WriteLine("<br />Regards,<br />");
                htmltw.WriteLine("UMS<br /><br />");
                htmltw.WriteLine("<b>-----------------------------------------------------------");
                htmltw.WriteLine("<br />This is an autogenerated mail, please do not reply.<br />");
                htmltw.WriteLine("-----------------------------------------------------------</b>");
                htmltw.RenderEndTag();
                htmltw.RenderEndTag();

                if (sendTo.StartsWith(","))
                    sendTo = sendTo.Remove(0, 1);

                if (sendTo.EndsWith(","))
                    sendTo = sendTo.Remove(sendTo.Length - 1, 1);

                if (sendTo != "")
                    objEmail.To.Add(sendTo);

                objEmail.Subject = sendSubject;
                objEmail.Body = sw.ToString();
                objEmail.IsBodyHtml = true;
                objEmail.Priority = System.Net.Mail.MailPriority.Normal;
                var fromAddress = System.Configuration.ConfigurationManager.AppSettings["FromAddress"].ToString();
                string fromPassword = System.Configuration.ConfigurationManager.AppSettings["FromAddressPwd"].ToString();
                var smtp = new System.Net.Mail.SmtpClient();
                {
                    smtp.Host = System.Configuration.ConfigurationManager.AppSettings["SMTPHost"].ToString();
                    smtp.Port = Convert.ToInt32(System.Configuration.ConfigurationManager.AppSettings["SMTPPort"]);
                    smtp.EnableSsl = false;
                    smtp.DeliveryMethod = System.Net.Mail.SmtpDeliveryMethod.Network;
                    smtp.Credentials = new NetworkCredential(fromAddress, fromPassword);
                    //smtp.Timeout = Convert.ToInt32(System.Configuration.ConfigurationManager.AppSettings["ServerTimeout"]);
                }
                smtp.Send(objEmail);
                //BusinessLayer.Alert.ShowSuccess("Mail sent successfully");
            }
            catch (Exception ex)
            {
                throw ex;
            }

        }
        public static void SendEmails(string sendTo, string sendSubject, string strArea, bool mailLinkToBeGiven = true)
        {
            try
            {
                System.Net.Mail.MailMessage objEmail = new System.Net.Mail.MailMessage();
                StringWriter sw = new StringWriter();
                HtmlTextWriter htmltw = new HtmlTextWriter(sw);
                htmltw.RenderBeginTag("html");
                htmltw.RenderBeginTag("body");
                htmltw.WriteLine(strArea + "<br />");

                if (mailLinkToBeGiven)
                    htmltw.WriteLine("<br />Please refer on-line application <a href = " + System.Configuration.ConfigurationManager.AppSettings["AppURL"].ToString() + ">" + System.Configuration.ConfigurationManager.AppSettings["AppURL"].ToString() + "</a> for further details.<br />");

                htmltw.WriteLine("<br />Regards,<br />");
                htmltw.WriteLine("IUFMP Web mail service<br /><br />");
                htmltw.WriteLine("<b>-----------------------------------------------------------");
                htmltw.WriteLine("<br />This is an autogenerated mail, please do not reply.<br />");
                htmltw.WriteLine("-----------------------------------------------------------</b>");
                htmltw.RenderEndTag();
                htmltw.RenderEndTag();

                if (sendTo.StartsWith(","))
                    sendTo = sendTo.Remove(0, 1);

                if (sendTo.EndsWith(","))
                    sendTo = sendTo.Remove(sendTo.Length - 1, 1);

                if (sendTo != "")
                    objEmail.To.Add(sendTo);

                objEmail.Subject = sendSubject;
                objEmail.Body = sw.ToString();
                objEmail.IsBodyHtml = true;
                objEmail.Priority = System.Net.Mail.MailPriority.Normal;
                var fromAddress = System.Configuration.ConfigurationManager.AppSettings["FromAddress"].ToString();
                string fromPassword = System.Configuration.ConfigurationManager.AppSettings["FromAddressPwd"].ToString();
                var smtp = new System.Net.Mail.SmtpClient();
                {
                    smtp.Host = System.Configuration.ConfigurationManager.AppSettings["SMTPHost"].ToString();
                    smtp.Port = Convert.ToInt32(System.Configuration.ConfigurationManager.AppSettings["SMTPPort"]);
                    smtp.EnableSsl = true;
                    smtp.DeliveryMethod = System.Net.Mail.SmtpDeliveryMethod.Network;
                    smtp.Credentials = new NetworkCredential(fromAddress, fromPassword);
                    smtp.Timeout = Convert.ToInt32(System.Configuration.ConfigurationManager.AppSettings["ServerTimeout"]);
                }
                smtp.Send(objEmail);
                //BusinessLayer.Alert.ShowSuccess("Mail sent successfully");
            }
            catch (Exception ex)
            {
                throw ex;
            }

        }

        public static void send_enrollment_email(string to, string name, string enrollment_number, string user_pwd, string program_name, string course_name, string pwd)
        {
            string email_id;
            string password;
            try
            {
                email_id = ConfigurationManager.AppSettings["email_id"];
                password = ConfigurationManager.AppSettings["email_id_password"];
                string textBody = null;
                using (MailMessage mm = new MailMessage(email_id, to))
                {

                    mm.Subject = "Enrollment number !! This is a unique identity";
                    textBody += "Dear " + "\r\n" + name + "\r\n" + ",<br>Congratulations!!!\r\n\r\n<br><br>" + "These are your Confidential details. You will login using enrollment number  \r\n</b><br>";
                    textBody += "\r\n\r\n<br>" + "Your enrollment number : " + "\r\n" + "<b>" + enrollment_number + "</b>" + " for your course " + "<b>" + course_name + "</b>" + " in programme " + "<b>" + program_name + "</b>" + "\r\n\r\n<br> is approved by your coordinator.<br><br>";

                    textBody += "Your username : " + "<b>" + enrollment_number + "</b>" + " \r\n</b>.<br>";
                    textBody += "Your password : " + "<b>" + user_pwd + "</b>" + " \r\n</b>.";
                    //textBody += "\r\n\r\n<br>" + "Your OTP is : " + "\r\n" + "<b>" + otp + "</b>" + "\r\n\r\n<br>";
                    textBody += "\r\n\r\n<br><br>" + "Note : " + "This is an only way where you will get login into your account";
                    //textBody += "\r\n\r\n<br><br>" + "If you have any questions leading up to the Beat Planner, feel free to reply to this email." + "\r\n\r\n<br><br>" + "We look forward to seeing you on" + "\r\n\r\n<b>" + " Beat Planner!" + "\r\n\r\n</b>";
                    textBody += "\r\n\r\n <br><br><br><br><br><br>" + "Thanks & Regards," + "\r\n\r\n<br><b>" + "\r\n<br>" + "Excel Geomatics Private Ltd, Noida" + "\r\n\r\n<br><b><br><br><br>";

                    textBody += "<b>" + "Confidentiality Notice: " + "</b>" + "This e-mail message, including any attachments, is for the sole use of the intended recipient(s) and may contain confidential and privileged information. Any unauthorized review, use, disclosure or distribution is prohibited. If you are not the intended recipient, please contact the sender by reply e-mail and destroy all copies of the original message. Please do not print this email unless it is absolutely necessary. Spread environmental awareness.";

                    mm.Body = textBody;
                    mm.IsBodyHtml = true;
                    SmtpClient smtp = new SmtpClient();
                    smtp.Host = "mail.edusokouniversity.edu.ng";
                    //smtp.EnableSsl = true;
                    NetworkCredential NetworkCred = new NetworkCredential(email_id, password);
                    smtp.UseDefaultCredentials = true;
                    smtp.Credentials = NetworkCred;
                    smtp.Port = 464;
                    //smtp.Timeout = 300000;
                    smtp.Send(mm);
                    //registration_log(mm.Subject.ToString(), mm.Body.ToString());
                }
            }
            catch (Exception ex)
            {

            }
        }

        public static void send_email(string to, string content, string name)
        {
            //testmail();
            string email_id;
            string password;
            try
            {
                ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls12;

                email_id = ConfigurationManager.AppSettings["email_id"];
                password = ConfigurationManager.AppSettings["email_id_password"];

                string textBody = string.Empty; // Initialize as empty string

                using (MailMessage mm = new MailMessage(email_id, to))
                {
                    mm.Subject = "Sharing the information to the user";

                    textBody = $"Dear {name},<br><br>" +
                              $"<b>{content}</b><br><br>" +
                              $"Thanks & Regards,<br><br><b>Excel Geomatics Private Ltd, Noida</b><br><br>" +
                              $"<b>Confidentiality Notice:</b> This e-mail message, including any attachments, " +
                              "is for the sole use of the intended recipient(s) and may contain confidential and privileged information. " +
                              "Any unauthorized review, use, disclosure, or distribution is prohibited. If you are not the intended recipient, " +
                              "please contact the sender by reply e-mail and destroy all copies of the original message. Please do not print this email " +
                              "unless it is absolutely necessary. Spread environmental awareness.";

                    mm.Body = textBody;
                    mm.IsBodyHtml = true;

                    SmtpClient smtp = new SmtpClient
                    {
                        Host = "smtp.hostinger.com",
                        Port = 587, // or 465 if using SSL
                        EnableSsl = true, // Set to true if using SSL/TLS
                        UseDefaultCredentials = false,
                        Credentials = new NetworkCredential(email_id, password),
                        Timeout = 300000 // Optional, 5 minutes
                    };

                    smtp.Send(mm);
                    Console.WriteLine("Email sent successfully.");
                }
            }
            catch (SmtpException smtpEx)
            {
                Console.WriteLine("SMTP Error: " + smtpEx.Message);
                if (smtpEx.InnerException != null)
                {
                    Console.WriteLine("Inner Exception: " + smtpEx.InnerException.Message);
                }
            }
            catch (Exception ex)
            {
                Console.WriteLine("An error occurred: " + ex.Message);
            }
            //try
            //{

            //    email_id = ConfigurationManager.AppSettings["email_id"];
            //    password = ConfigurationManager.AppSettings["email_id_password"];
            //    string textBody = null;
            //    using (MailMessage mm = new MailMessage(email_id, to))
            //    {

            //        mm.Subject = "One Time Password !! Don't Share With Anyone";
            //        textBody += "Dear " + "\r\n" + name + "\r\n" + ",\r\n\r\n<br><br>" + "This is your Registration number. You can login using registration number  \r\n</b>";
            //        textBody += "\r\n\r\n<br>" + "Your registration number : " + "\r\n" + "<b>" + registration_no + "</b>" + "\r\n\r\n<br>";

            //        textBody += "This is your one time password (OTP). Do not share with anyone \r\n</b>";
            //        textBody += "\r\n\r\n<br>" + "\r\n"+"<b>" + otp + "</b>"+"\r\n\r\n<br>";
            //        //textBody += "\r\n\r\n<br><br>" + "This OTP is only for verification of your email.";
            //        //textBody += "\r\n\r\n<br><br>" + "If you have any questions leading up to the Beat Planner, feel free to reply to this email." + "\r\n\r\n<br><br>" + "We look forward to seeing you on" + "\r\n\r\n<b>" + " Beat Planner!" + "\r\n\r\n</b>";
            //        textBody += "\r\n\r\n <br><br><br><br><br><br>" + "Thanks & Regards," + "\r\n\r\n<br><b>"  + "\r\n<br>" + "Excel Geomatics Private Ltd, Noida" + "\r\n\r\n<br><b><br><br><br>"; 

            //        textBody += "<b>" + "Confidentiality Notice: " + "</b>" + "This e-mail message, including any attachments, is for the sole use of the intended recipient(s) and may contain confidential and privileged information. Any unauthorized review, use, disclosure or distribution is prohibited. If you are not the intended recipient, please contact the sender by reply e-mail and destroy all copies of the original message. Please do not print this email unless it is absolutely necessary. Spread environmental awareness.";

            //        mm.Body = textBody;
            //        mm.IsBodyHtml = true;
            //        SmtpClient smtp = new SmtpClient();
            //        smtp.Host = "mail.edusokouniversity.edu.ng";
            //        //smtp.EnableSsl = true;
            //        NetworkCredential NetworkCred = new NetworkCredential(email_id, password);
            //        smtp.UseDefaultCredentials = true;
            //        smtp.Credentials = NetworkCred;
            //        smtp.Port = 587;
            //        smtp.EnableSsl = true;
            //        //smtp.Timeout = 300000;
            //        smtp.Send(mm);
            //        //registration_log(mm.Subject.ToString(), mm.Body.ToString());
            //    }
            //}
            //catch(Exception ex)
            //{

            //}
        }

        public static void SendEmail(string to, string content, string name, string documentPath = null)
        {
            string email_id;
            string password;
            try
            {
                ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls12;

                email_id = ConfigurationManager.AppSettings["email_id"];
                password = ConfigurationManager.AppSettings["email_id_password"];

                string textBody = string.Empty; // Initialize as empty string

                using (MailMessage mm = new MailMessage(email_id, to))
                {
                    mm.Subject = "Sharing the information with the user";

                    textBody = $"Dear {name},<br><br>" +
                                $"<b>{content}</b><br><br>" +
                                $"Thanks & Regards,<br><br><b>Excel Geomatics Private Ltd, Noida</b><br><br>" +
                                $"<b>Confidentiality Notice:</b> This e-mail message, including any attachments, " +
                                "is for the sole use of the intended recipient(s) and may contain confidential and privileged information. " +
                                "Any unauthorized review, use, disclosure, or distribution is prohibited. If you are not the intended recipient, " +
                                "please contact the sender by reply e-mail and destroy all copies of the original message. Please do not print this email " +
                                "unless it is absolutely necessary. Spread environmental awareness.";

                    mm.Body = textBody;
                    mm.IsBodyHtml = true;

                    // Attach document if provided
                    if (!string.IsNullOrEmpty(documentPath) && System.IO.File.Exists(documentPath))
                    {
                        Attachment attachment = new Attachment(documentPath);
                        mm.Attachments.Add(attachment);
                    }

                    SmtpClient smtp = new SmtpClient
                    {
                        Host = "smtp.hostinger.com",
                        Port = 587, // or 465 if using SSL
                        EnableSsl = true, // Set to true if using SSL/TLS
                        UseDefaultCredentials = false,
                        Credentials = new NetworkCredential(email_id, password),
                        Timeout = 300000 // Optional, 5 minutes
                    };

                    smtp.Send(mm);
                    Console.WriteLine("Email sent successfully.");
                }
            }
            catch (SmtpException smtpEx)
            {
                Console.WriteLine("SMTP Error: " + smtpEx.Message);
                if (smtpEx.InnerException != null)
                {
                    Console.WriteLine("Inner Exception: " + smtpEx.InnerException.Message);
                }
            }
            catch (Exception ex)
            {
                Console.WriteLine("An error occurred: " + ex.Message);
            }
        }

        public static void testmail()
        {
            string smtpServer = "mail.edusokouniversity.edu.ng"; // Replace with your SMTP server
            int smtpPort = 464; // Common ports are 25, 587, 465 (SSL/TLS)
            string smtpUser = "passwordreset@edusokouniversity.edu.ng"; // Replace with your SMTP username
            string smtpPass = "passreset@eub"; // Replace with your SMTP password

            // Email details
            string fromEmail = "passwordreset@edusokouniversity.edu.ng"; // Replace with your email address
            string toEmail = "kamil.khan@excelgeomatics.in"; // Replace with recipient's email address
            string subject = "Test Email";
            string body = "This is a test email sent from C#.";

            try
            {
                // Create a new mail message
                MailMessage mail = new MailMessage
                {
                    From = new MailAddress(fromEmail),
                    Subject = subject,
                    Body = body
                };
                mail.To.Add(toEmail);

                // Create an SMTP client
                SmtpClient smtpClient = new SmtpClient(smtpServer, smtpPort)
                {
                    Credentials = new NetworkCredential(smtpUser, smtpPass),
                    EnableSsl = true // Enable SSL/TLS if required by your server
                };

                // Optionally, validate server certificate (for development/testing only)
                ServicePointManager.ServerCertificateValidationCallback = (sender, certificate, chain, sslPolicyErrors) =>
                {
                    return true; // WARNING: Accepts any certificate, use for development only
                };

                // Send the email
                smtpClient.Send(mail);

                Console.WriteLine("Email sent successfully.");
            }
            catch (SmtpException smtpEx)
            {
                Console.WriteLine("SMTP Error: " + smtpEx.Message);
                if (smtpEx.InnerException != null)
                {
                    Console.WriteLine("Inner Exception: " + smtpEx.InnerException.Message);
                }
            }
            catch (Exception ex)
            {
                Console.WriteLine("An error occurred: " + ex.Message);
            }
        }

        public static void send_email(string to, string name, string otp, string pwd)
        {
            string email_id;
            string password;
            try
            {
                email_id = ConfigurationManager.AppSettings["email_id"];
                password = ConfigurationManager.AppSettings["email_id_password"];
                string textBody = null;
                using (MailMessage mm = new MailMessage(email_id, to))
                {
                    mm.Subject = "Principal information";
                    textBody = "Dear " + "\r\n" + name + "\r\n" + ",\r\n\r\n<br><br>";
                    textBody += "\r\n\r\n<br>" + "<b>" + otp + "</b>" + "\r\n\r\n<br>";
                    // textBody += "\r\n\r\n<br><br>" + "This OTP is only for verification of your email.";
                    //textBody += "\r\n\r\n<br><br>" + "If you have any questions leading up to the Beat Planner, feel free to reply to this email." + "\r\n\r\n<br><br>" + "We look forward to seeing you on" + "\r\n\r\n<b>" + " Beat Planner!" + "\r\n\r\n</b>";
                    textBody += "\r\n\r\n <br><br><br><br><br><br>" + "Thanks & Regards," + "\r\n\r\n<br><b>" + "\r\n<br>" + "Excel Geomatics Private Ltd, Noida" + "\r\n\r\n<br><b><br><br><br>";
                    textBody += "<b>" + "Confidentiality Notice: " + "</b>" + "This e-mail message, including any attachments, is for the sole use of the intended recipient(s) and may contain confidential and privileged information. Any unauthorized review, use, disclosure or distribution is prohibited. If you are not the intended recipient, please contact the sender by reply e-mail and destroy all copies of the original message. Please do not print this email unless it is absolutely necessary. Spread environmental awareness.";

                    mm.Body = textBody;
                    mm.IsBodyHtml = true;
                    SmtpClient smtp = new SmtpClient();
                    smtp.Host = "mail.edusokouniversity.edu.ng";
                    //smtp.EnableSsl = true;
                    NetworkCredential NetworkCred = new NetworkCredential(email_id, password);
                    smtp.UseDefaultCredentials = true;
                    smtp.Credentials = NetworkCred;
                    smtp.Port = 464;
                    //smtp.Timeout = 300000;
                    smtp.Send(mm);
                    //registration_log(mm.Subject.ToString(), mm.Body.ToString());
                }
            }
            catch (Exception ex)
            {

            }
        }




        public static void send_mail_for_user_credential(string to, string name, string websiteUrl, string userId, string user_pwd)
        {
            //testmail();
            string email_id;
            string password;
            try
            {
                ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls12;

                email_id = ConfigurationManager.AppSettings["email_id"];
                password = ConfigurationManager.AppSettings["email_id_password"];

                string textBody = string.Empty; // Initialize as empty string

                using (MailMessage mm = new MailMessage(email_id, to))
                {
                    mm.Subject = "Sharing the information to the user";

                    textBody = $"Dear {name},<br><br>" +
                  $"<b>You have been successfully registered on our website. Below are your login credentials:</b><br><br>" +
                  $"<b>Website:</b> {websiteUrl}<br>" +
                  $"<b>User ID:</b> {userId}<br>" +
                  $"<b>Password:</b> {user_pwd}<br><br>" +
                  $"Please keep this information confidential. You can log in at any time using the link above. " +
                  $"For your security, we recommend changing your password after your first login.<br><br>" +
                  $"Thanks & Regards,<br><br><b>Excel Geomatics Private Ltd, Noida</b><br><br>" +
                  $"<b>Confidentiality Notice:</b> This e-mail message, including any attachments, " +
                  "is for the sole use of the intended recipient(s) and may contain confidential and privileged information. " +
                  "Any unauthorized review, use, disclosure, or distribution is prohibited. If you are not the intended recipient, " +
                  "please contact the sender by reply e-mail and destroy all copies of the original message. Please do not print this email " +
                  "unless it is absolutely necessary. Spread environmental awareness.";

                    mm.Body = textBody;
                    mm.IsBodyHtml = true;

                    SmtpClient smtp = new SmtpClient
                    {
                        Host = "smtp.hostinger.com",
                        Port = 587, // or 465 if using SSL
                        EnableSsl = true, // Set to true if using SSL/TLS
                        UseDefaultCredentials = false,
                        Credentials = new NetworkCredential(email_id, password),
                        Timeout = 300000 // Optional, 5 minutes
                    };

                    smtp.Send(mm);
                    Console.WriteLine("Email sent successfully.");
                }
            }
            catch (SmtpException smtpEx)
            {
                Console.WriteLine("SMTP Error: " + smtpEx.Message);
                if (smtpEx.InnerException != null)
                {
                    Console.WriteLine("Inner Exception: " + smtpEx.InnerException.Message);
                }
            }
            catch (Exception ex)
            {
                Console.WriteLine("An error occurred: " + ex.Message);
            }
        }


        public static void send_mail_to_group(string to, string group_name, string name, string websiteUrl, string userId, string user_role_name)
        {
            string email_id;
            string password;
            try
            {
                ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls12;

                email_id = ConfigurationManager.AppSettings["email_id"];
                password = ConfigurationManager.AppSettings["email_id_password"];

                string textBody = string.Empty;

                using (MailMessage mm = new MailMessage(email_id, to))
                {
                    mm.Subject = "Notification: New User Added Under Your Supervision as " + user_role_name;

                    textBody = $"Dear {group_name},<br><br>" +
                        $"We would like to inform you that a new user has been added under your supervision.<br><br>" +
                        $"<b>Added User ID:</b> {userId}<br>" +
                        $"<b>Added User Name:</b> {name}<br><br>" +
                        $"<b>Higher Authority Name (You):</b> {group_name}<br><br>" +
                        $"<b>Higher Authority Email (You):</b> {to}<br><br>" +
                        $"You can review their information into the system: <a href='{websiteUrl}'>{websiteUrl}</a>.<br><br>" +
                        $"Thanks & Regards,<br><br><b>Excel Geomatics Private Ltd, Noida</b><br><br>" +
                        $"<b>Confidentiality Notice:</b> This e-mail message, including any attachments, " +
                        "is for the sole use of the intended recipient(s) and may contain confidential and privileged information. " +
                        "Any unauthorized review, use, disclosure, or distribution is prohibited. If you are not the intended recipient, " +
                        "please contact the sender by reply e-mail and destroy all copies of the original message. Please do not print this email " +
                        "unless it is absolutely necessary. Spread environmental awareness.";

                    mm.Body = textBody;
                    mm.IsBodyHtml = true;

                    SmtpClient smtp = new SmtpClient
                    {
                        Host = "smtp.hostinger.com",
                        Port = 587,
                        EnableSsl = true,
                        UseDefaultCredentials = false,
                        Credentials = new NetworkCredential(email_id, password),
                        Timeout = 300000
                    };

                    smtp.Send(mm);
                    Console.WriteLine("Email sent successfully.");
                }
            }
            catch (SmtpException smtpEx)
            {
                Console.WriteLine("SMTP Error: " + smtpEx.Message);
                if (smtpEx.InnerException != null)
                {
                    Console.WriteLine("Inner Exception: " + smtpEx.InnerException.Message);
                }
            }
            catch (Exception ex)
            {
                Console.WriteLine("An error occurred: " + ex.Message);
            }
        }


    }
}